CREATE DATABASE IF NOT EXISTS auth_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS product_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS order_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS pay_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS seckill_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS logistics_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS notify_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'shop'@'%' IDENTIFIED BY 'shop123456';
GRANT ALL PRIVILEGES ON auth_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON product_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON order_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON pay_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON seckill_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON logistics_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON notify_db.* TO 'shop'@'%';
FLUSH PRIVILEGES;

